-- Enry Lab — Skill Prompt Forge schema
-- Tracks every skill invocation, explicit/implicit outcome signals, and
-- proposed/approved/rejected prompt revisions.

-- Explicit feedback values
CREATE TYPE skill_feedback AS ENUM ('helpful', 'missed', 'corrected');
-- Revision lifecycle
CREATE TYPE revision_status AS ENUM ('proposed', 'approved', 'rejected');

-- Every time a skill is invoked (Drive or chat), we log it here.
CREATE TABLE skill_invocations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skill_slug text NOT NULL,
  prompt_version text NOT NULL DEFAULT 'base',
  input_topic text NOT NULL DEFAULT '',
  output_text text NOT NULL DEFAULT '',
  model_used text,
  effort_used text,
  mode text,
  source text NOT NULL DEFAULT 'unknown', -- 'drive' | 'chat' | 'other'
  explicit_feedback skill_feedback,
  implicit_score smallint DEFAULT 0,
  conversation_id text,
  follow_up_message_id text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Proposed prompt revisions generated by the review pass.
CREATE TABLE skill_prompt_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  skill_slug text NOT NULL,
  old_prompt text NOT NULL,
  proposed_prompt text NOT NULL,
  reasoning text NOT NULL DEFAULT '',
  status revision_status NOT NULL DEFAULT 'proposed',
  override_active boolean NOT NULL DEFAULT false,
  sample_invocation_ids uuid[] DEFAULT '{}',
  win_rate_before real,
  estimated_win_rate_after real,
  proposed_at timestamptz NOT NULL DEFAULT now(),
  reviewed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX idx_skill_invocations_user_slug ON skill_invocations(user_id, skill_slug);
CREATE INDEX idx_skill_invocations_created_at ON skill_invocations(created_at DESC);
CREATE INDEX idx_skill_invocations_feedback ON skill_invocations(user_id, explicit_feedback, created_at DESC);
CREATE INDEX idx_skill_prompt_revisions_slug ON skill_prompt_revisions(user_id, skill_slug);
CREATE INDEX idx_skill_prompt_revisions_active ON skill_prompt_revisions(skill_slug, override_active) WHERE override_active = true;

-- Row Level Security
ALTER TABLE skill_invocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE skill_prompt_revisions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only see their own skill invocations"
  ON skill_invocations FOR ALL
  USING (auth.uid() = user_id);

CREATE POLICY "Users can only see their own skill prompt revisions"
  ON skill_prompt_revisions FOR ALL
  USING (auth.uid() = user_id);

-- Updated-at trigger helper
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_skill_invocations_updated_at
  BEFORE UPDATE ON skill_invocations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_skill_prompt_revisions_updated_at
  BEFORE UPDATE ON skill_prompt_revisions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
