// ───────────────────────────────────────────────────────────────────
// StreamMerger — cleanly appends recovery text to existing content
// without duplicating markdown structures, code blocks, or headings.
//
// When a stream is interrupted mid-generation and recovery generates
// new text, the two pieces need to be merged so the user sees a single
// coherent response. The merger handles:
//
//   - Removing duplicate opening/closing paragraphs
//   - Not breaking mid-word (joins at word boundary)
//   - Preserving code block integrity (no orphan fences)
//   - Removing recovery artifacts (apologies, acknowledgements)
// ───────────────────────────────────────────────────────────────────

/** Patterns that indicate the model is restarting instead of continuing. */
const RESTART_PATTERNS = [
  /^(I (apologize|'m sorry|beg your pardon)[^.]*\.?)\s*/i,
  /^(Let me (start over|restart|begin again)[^.]*\.?)\s*/i,
  /^(Here('s| is) the (complete|full|corrected) (response|answer)[:]*)\s*/i,
  /^(I('ll| will) (try again|restart|re-attempt)[^.]*\.?)\s*/i,
  /^(It seems my (previous|last|earlier) response was interrupted[^.]*\.?)\s*/i,
]

/** Headings that likely indicate the start of a duplicated section. */
const HEADING_PATTERNS = /^(#{1,6}\s+.+)$/gm

/**
 * Merge partial content with recovery content into a single clean output.
 *
 * @param partial - The text that was already streamed before interruption.
 * @param recovery - The text generated by the recovery strategy.
 * @returns The merged text with duplicates and artifacts removed.
 */
export function mergeRecoveryContent(partial: string, recovery: string): string {
  if (!partial) return cleanRecoveryText(recovery)
  if (!recovery) return partial.trimEnd()

  const cleanRecovery = cleanRecoveryText(recovery)
  if (!cleanRecovery) return partial.trimEnd()

  const partialEnd = partial.trimEnd()
  const recoveryStart = cleanRecovery.trimStart()

  // ── 1. Handle incomplete markdown fences ─────────────────────────
  const partialFences = (partialEnd.match(/```/g) || []).length
  const recoveryFences = (recoveryStart.match(/```/g) || []).length

  // If the partial ends inside a code block (odd number of fences),
  // and recovery starts outside one, merge them cleanly
  if (partialFences % 2 === 1 && recoveryStart.startsWith('```')) {
    // Partial is inside a code block. Recovery starts with a new fence.
    // Close the partial's code block and let recovery open a new one.
    return partialEnd + '\n```\n\n' + recoveryStart
  }

  // If partial ends mid-codeblock and recovery doesn't start with a fence,
  // keep the code block open by appending directly
  if (partialFences % 2 === 1 && !recoveryStart.startsWith('```')) {
    return partialEnd + '\n' + recoveryStart
  }

  // ── 2. Remove duplicate opening from recovery ────────────────────

  // Try to find overlap between the end of partial and start of recovery
  const overlap = findOverlap(partialEnd, recoveryStart)
  if (overlap.length > 10) {
    // There's significant overlap — trim the duplicate from recovery
    const trimmed = recoveryStart.slice(overlap.length).trimStart()
    if (trimmed) {
      return partialEnd + trimmed
    }
    // If nothing left after trimming overlap, just return partial
    return partialEnd
  }

  // ── 3. Join at word boundary ─────────────────────────────────────
  const partialLastWord = partialEnd.slice(-30)
  const recoveryFirstWord = recoveryStart.slice(0, 30)

  // If partial ends mid-word and recovery starts with the remainder
  const partialLastWordTrimmed = partialLastWord.trimEnd()
  if (
    partialLastWordTrimmed &&
    recoveryFirstWord.toLowerCase().includes(partialLastWordTrimmed.slice(-5).toLowerCase())
  ) {
    // Likely a word continuation — join without space
    const joinPoint = partialLastWordTrimmed.length
    const joined = partialEnd.slice(0, -joinPoint) + recoveryStart
    return joined
  }

  // Default: join with a single space if partial doesn't end with one
  const separator = partialEnd.endsWith('\n') || partialEnd.endsWith(' ') ? '' : ' '
  return partialEnd + separator + recoveryStart
}

/**
 * Clean recovery text — remove restart apologies and duplicated headings.
 */
export function cleanRecoveryText(text: string): string {
  let cleaned = text.trim()

  // Remove restart apologies
  for (const pattern of RESTART_PATTERNS) {
    cleaned = cleaned.replace(pattern, '')
  }

  // Remove standalone "---" separators that the model might add
  cleaned = cleaned.replace(/^---+\s*/m, '')

  // Remove "CONTINUATION:" or "[CONTINUED]" markers
  cleaned = cleaned.replace(/\[?CONTINU(ED|ATION|ING)\]?/gi, '')
  cleaned = cleaned.replace(/^CONTINUATION:?\s*/m, '')

  return cleaned.trim()
}

/**
 * Find overlapping text between the end of `a` and the start of `b`.
 * Returns the longest overlapping substring.
 */
function findOverlap(a: string, b: string): string {
  const maxOverlap = Math.min(a.length, b.length, 100) // Don't search too far
  for (let len = maxOverlap; len >= 5; len--) {
    const suffix = a.slice(-len)
    if (b.startsWith(suffix)) {
      return suffix
    }
  }
  return ''
}

/**
 * Check if recovery produced duplicate content compared to the partial.
 */
export function hasDuplicateContent(partial: string, recovery: string): boolean {
  if (!partial || !recovery) return false

  const partialWords = new Set(
    partial.toLowerCase().match(/\b\w{4,}\b/g) || [],
  )
  const recoveryWords = recovery.toLowerCase().match(/\b\w{4,}\b/g) || []

  if (recoveryWords.length === 0) return false

  const commonWords = recoveryWords.filter((w) => partialWords.has(w))
  // If >70% of unique recovery words are in the partial, it's a duplicate
  const uniqueRecovery = new Set(recoveryWords)
  const duplicateRatio =
    commonWords.filter((w, i, arr) => arr.indexOf(w) === i).length /
    uniqueRecovery.size

  return duplicateRatio > 0.7
}
